name: "Registering a developer"

on:
    issues:

permissions: 
    issues: read
    contents: write


jobs:
    get-json:
        name: "Get Issue form JSON"
        runs-on: ubuntu-latest
        steps:             
            - name: GitHub Issue Forms Body Parser
              id: body-parser
              uses: zentered/issue-forms-body-parser@v2.2.0
            - run: echo ${{ toJSON(steps.body-parser.outputs.data) }}

            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
            - name: Write File
              uses: DamianReeves/write-file-action@v1.2
              with:
                  write-mode: overwrite
                  path: ./{{ toJSON(step.body-parser.outputs.json)[0]}}/{{ steps.date.outputs.date }}.json
                  contents: ${{ steps.body-parser.outputs.json }}
            - name: Commit and push
              uses: Andro999b/push@v1.3
              with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    branch: main
                    force: true
                    message: "chore: add {{ toJSON(step.body-parser.outputs.json)[0]}}/{{ steps.date.outputs.date }}.json"
            
